// Shared nanny/caregiver data used across the marketplace.
// In production this would come from the database (MongoDB) via /app/api routes.

export const LANGUAGE_LABELS = {
  en: 'English',
  es: 'Español',
  pt: 'Português',
  he: 'עברית',
};

export const NANNIES = [
  {
    id: 1,
    name: 'María García',
    initials: 'MG',
    color: 'from-upa-pink to-upa-pinkdark',
    rating: 4.9,
    reviews: 28,
    hourlyRate: 18,
    services: ['Babysitting', 'Tutoring'],
    experience: 8,
    languages: ['en', 'es'],
    neighborhood: 'Brickell',
    location: { lat: 25.7617, lng: -80.1918 },
    badges: { idVerified: true, backgroundCheck: true, cprCertified: true },
    sameDayAvailable: true,
    familiesRecommended: 12,
  },
  {
    id: 2,
    name: 'Sarah Johnson',
    initials: 'SJ',
    color: 'from-upa-ink to-slate-600',
    rating: 4.8,
    reviews: 42,
    hourlyRate: 20,
    services: ['Babysitting', 'Cooking'],
    experience: 10,
    languages: ['en'],
    neighborhood: 'Coral Gables',
    location: { lat: 25.7215, lng: -80.2684 },
    badges: { idVerified: true, backgroundCheck: true, cprCertified: true },
    sameDayAvailable: false,
    familiesRecommended: 19,
  },
  {
    id: 3,
    name: 'Rosa López',
    initials: 'RL',
    color: 'from-upa-mint to-emerald-600',
    rating: 4.9,
    reviews: 35,
    hourlyRate: 19,
    services: ['Babysitting', 'Homework Help'],
    experience: 9,
    languages: ['en', 'es'],
    neighborhood: 'Doral',
    location: { lat: 25.8195, lng: -80.3553 },
    badges: { idVerified: true, backgroundCheck: true, cprCertified: false },
    sameDayAvailable: true,
    familiesRecommended: 15,
  },
  {
    id: 4,
    name: 'Emma Wilson',
    initials: 'EW',
    color: 'from-upa-pink to-upa-pinkdark',
    rating: 4.7,
    reviews: 21,
    hourlyRate: 17,
    services: ['Babysitting'],
    experience: 5,
    languages: ['en', 'he'],
    neighborhood: 'Aventura',
    location: { lat: 25.9565, lng: -80.1392 },
    badges: { idVerified: true, backgroundCheck: true, cprCertified: false },
    sameDayAvailable: true,
    familiesRecommended: 8,
  },
  {
    id: 5,
    name: 'Carmen Rodríguez',
    initials: 'CR',
    color: 'from-upa-ink to-slate-700',
    rating: 5.0,
    reviews: 15,
    hourlyRate: 22,
    services: ['Babysitting', 'Tutoring', 'Cooking'],
    experience: 12,
    languages: ['en', 'es', 'pt'],
    neighborhood: 'Miami Beach',
    location: { lat: 25.7907, lng: -80.1300 },
    badges: { idVerified: true, backgroundCheck: true, cprCertified: true },
    sameDayAvailable: false,
    familiesRecommended: 22,
  },
  {
    id: 6,
    name: 'Ana Sofía Pérez',
    initials: 'AP',
    color: 'from-upa-mint to-teal-600',
    rating: 4.8,
    reviews: 19,
    hourlyRate: 16,
    services: ['Babysitting', 'Homework Help'],
    experience: 4,
    languages: ['en', 'es'],
    neighborhood: 'Kendall',
    location: { lat: 25.6795, lng: -80.3173 },
    badges: { idVerified: true, backgroundCheck: true, cprCertified: true },
    sameDayAvailable: true,
    familiesRecommended: 6,
  },
];

export function getFeaturedNannies(count = 3) {
  return [...NANNIES].sort((a, b) => b.rating - a.rating).slice(0, count);
}
